### ISSUE TITLE
Strange Start-up error?

### ISSUE THREAD

**Issue by zerafox** [Daniel12321/AdventureMMO#10]
I'm getting this error on startup, and I'm not sure why it's popping up in my console. It appears to work just fine ingame, although I haven't paid too much attention after breaking/using new blocks/items from other mods such as Biomes o' Plenty.

30.11 22:04:11 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111] 30.11 22:04:11 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] 30.11 22:04:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?] 30.11 22:04:11 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?] 30.11 22:04:11 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:94) [EventBus.class:?] 30.11 22:04:11 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:125) [EventBus.class:?] 30.11 22:04:11 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?] 30.11 22:04:11 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_9_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?] 30.11 22:04:11 [Server] INFO at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:258) [SpongeMod.class:1.10.2-2123-5.1.0-BETA-1879] 30.11 22:04:11 [Server] INFO at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2123-5.1.0-BETA-1879] 30.11 22:04:11 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.10.2-2123-5.1.0-BETA-1879] 30.11 22:04:11 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) [SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1879] 30.11 22:04:11 [Server] INFO at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_111] 30.11 22:04:11 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) ~[SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1879] 30.11 22:04:11 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1879] 30.11 22:04:11 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.10.2-2123-5.1.0-BETA-1879] 30.11 22:04:11 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1879] 30.11 22:04:11 [Server] INFO at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2123-5.1.0-BETA-1879] 30.11 22:04:11 [Server] INFO at me.mrdaniel.mmo.listeners.WorldListener.lambda$onEntitySpawn$0(WorldListener.java:81) ~[WorldListener.class:?] 30.11 22:04:11 [Server] INFO at net.minecraft.entity.item.EntityItem.getItemData(EntityItem.java:228) ~[yk.class:?] 30.11 22:04:11 [Server] INFO at org.spongepowered.common.item.inventory.util.ItemStackUtil.createSnapshot(ItemStackUtil.java:124) ~[ItemStackUtil.class:1.10.2-2123-5.1.0-BETA-1879] 30.11 22:04:11 [Server] INFO at net.minecraft.item.ItemStack.createSnapshot(ItemStack.java:233) ~[adz.class:?] 30.11 22:04:11 [Server] INFO at org.spongepowered.common.item.inventory.SpongeItemStackSnapshot.<init>(SpongeItemStackSnapshot.java:92) ~[SpongeItemStackSnapshot.class:1.10.2-2123-5.1.0-BETA-1879] 30.11 22:04:11 [Server] INFO at net.minecraft.item.ItemStack.func_77952_i(ItemStack.java:244) ~[adz.class:?] 30.11 22:04:11 [Server] INFO java.lang.NullPointerException 30.11 22:04:11 [Server] Server thread/ERROR [Sponge]: The Scheduler tried to run the task adventuremmo-S-58 owned by Plugin{id=adventuremmo, name=AdventureMMO, version=1.6.3, source=/mods/MMO-v1.6.3-API5.0.jar}, but an error occured.

Any insight on if maybe I've done something funky, that'd be great.

**Comment by zerafox** [comment]
I was told I needed to update my SpongeForge by the Sponge Team, so I have done so and I updated MMO to the latest version as well. Hoping that perhaps the error would be resolved?
No such luck.

01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /******************************************************************************************************************/ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /* java.lang.Thread.run(Unknown Source) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:94) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:125) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:266) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / me.mrdaniel.mmo.listeners.WorldListener.lambda$onEntitySpawn$0(WorldListener.java:81) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / net.minecraft.entity.item.EntityItem.getItemData(EntityItem.java:228) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / org.spongepowered.common.item.inventory.util.ItemStackUtil.createSnapshot(ItemStackUtil.java:124) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / net.minecraft.item.ItemStack.createSnapshot(ItemStack.java:233) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / org.spongepowered.common.item.inventory.SpongeItemStackSnapshot.(SpongeItemStackSnapshot.java:87) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / net.minecraft.item.ItemStack.getContainers(ItemStack.java:254) / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / java.lang.Exception: null / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / Printing a Stacktrace: / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / Please ask help for seeing if this is an issue with a mod and report it! / 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / An ItemStack has a null ItemType! This is usually not supported as it will likely have issues elsewhere. */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /************************************************************************************************************/ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: / Null Item found! */ 01.12 05:20:06 [Server] Server thread/WARN [Sponge]: /******************************************************************************************************************/ 01.12 05:20:06 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111] 01.12 05:20:06 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] 01.12 05:20:06 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:94) [EventBus.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:125) [EventBus.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?] 01.12 05:20:06 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?] 01.12 05:20:06 [Server] INFO at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:266) [SpongeMod.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) [SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_111] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) ~[SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at me.mrdaniel.mmo.listeners.WorldListener.lambda$onEntitySpawn$0(WorldListener.java:81) ~[WorldListener.class:?] 01.12 05:20:06 [Server] INFO at net.minecraft.entity.item.EntityItem.getItemData(EntityItem.java:228) ~[yk.class:?] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.item.inventory.util.ItemStackUtil.createSnapshot(ItemStackUtil.java:124) ~[ItemStackUtil.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at net.minecraft.item.ItemStack.createSnapshot(ItemStack.java:233) ~[adz.class:?] 01.12 05:20:06 [Server] INFO at org.spongepowered.common.item.inventory.SpongeItemStackSnapshot.(SpongeItemStackSnapshot.java:92) ~[SpongeItemStackSnapshot.class:1.10.2-2123-5.1.0-BETA-1925] 01.12 05:20:06 [Server] INFO at net.minecraft.item.ItemStack.func_77952_i(ItemStack.java:244) ~[adz.class:?] 01.12 05:20:06 [Server] INFO java.lang.NullPointerException 01.12 05:20:06 [Server] Server thread/ERROR [Sponge]: The Scheduler tried to run the task adventuremmo-S-2 owned by Plugin{id=adventuremmo, name=AdventureMMO, version=1.6.3, source=/mods/MMO-v1.6.3-API5.x.jar}, but an error occured.

**Comment by Daniel12321** [comment]
I will try to fix this error, however it looks like it wont break any part of the game or plugin.

**Comment by Daniel12321** [comment]
Fixed in the new code.
