### ISSUE TITLE
No Salvage Notification

### ISSUE THREAD

**Issue by zerafox** [Daniel12321/AdventureMMO#11]
There is a notification when repairing your items on an Iron Block, but no notification on the Gold Block when salvaging.

Could we get a notice for Salvaging too? Perhaps even a confirmation before destroying an item, I can foresee accidental Salvaging if you click the Gold when you meant Iron. Especially for folks who aren't used to the system.

**Comment by Daniel12321** [comment]
Will also do this in the next update

**Comment by EvilCh33z** [comment]
seconded
