### ISSUE TITLE
Cannot Interact: Error

### ISSUE THREAD

**Issue by zerafox** [Daniel12321/AdventureMMO#12]
I was minding my own business, developing my farm to feed myself and my cows when all of a sudden I couldn't plant my seeds anymore, out of no where. I also couldn't use my hoe to create more farmland, couldn't access my doors, chests, furnaces, anything.

01.12 03:37:58 [Server] INFO /***********************************************************************************************************************************/ 01.12 03:37:58 [Server] INFO /* java.lang.Thread.run(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.util.Util.func_181617_a(SourceFile:45) */ 01.12 03:37:58 [Server] INFO /* java.util.concurrent.FutureTask.run(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:130) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:190) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:320) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$47(PacketFunction.java:900) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache.get(LocalCache.java:3934) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.util.LanguageUtil$1.load(LanguageUtil.java:42) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.util.LanguageUtil$1.load(LanguageUtil.java:45) */ 01.12 03:37:58 [Server] INFO /* org.apache.commons.lang3.LocaleUtils.toLocale(LocaleUtils.java:142) */ 01.12 03:37:58 [Server] INFO /* java.lang.IllegalArgumentException: Invalid locale format: en_us */ 01.12 03:37:58 [Server] INFO /* java.lang.Thread.run(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.util.Util.func_181617_a(SourceFile:45) */ 01.12 03:37:58 [Server] INFO /* java.util.concurrent.FutureTask.run(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) */ 01.12 03:37:58 [Server] INFO /* net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:130) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:190) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:320) */ 01.12 03:37:58 [Server] INFO /* org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$47(PacketFunction.java:900) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache.get(LocalCache.java:3934) */ 01.12 03:37:58 [Server] INFO /* com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) */ 01.12 03:37:58 [Server] INFO /* com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Invalid locale format: en_us */ 01.12 03:37:58 [Server] INFO /* Stacktrace: */ 01.12 03:37:58 [Server] INFO /* Object: EntityItemEntityDropsSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedEntityItemDrops */ 01.12 03:37:58 [Server] INFO /* Object: EntityItemDropsSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedEntityItemDropMap */ 01.12 03:37:58 [Server] INFO /* Object: CapturedItemStackSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedItemStacks */ 01.12 03:37:58 [Server] INFO /* Object: CapturedEntitiesSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedEntities */ 01.12 03:37:58 [Server] INFO /* Object: CapturedItemsSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedItems */ 01.12 03:37:58 [Server] INFO /* Object: BlockItemDropsSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedBlockDropMap */ 01.12 03:37:58 [Server] INFO /* Object: BlockItemEntityDropsSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedBlockITemDrops */ 01.12 03:37:58 [Server] INFO /* Object: CapturedBlocksSupplier{Captured=0} */ 01.12 03:37:58 [Server] INFO /* - Name: CapturedBlocks */ 01.12 03:37:58 [Server] INFO /* Object: org.spongepowered.common.event.tracking.phase.packet.BasicPacketState@27dc5f75 */ 01.12 03:37:58 [Server] INFO /* - Name: UnwindingState */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Notifier */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Owner */ 01.12 03:37:58 [Server] INFO /* Object: false */ 01.12 03:37:58 [Server] INFO /* - Name: IgnoringCreative */ 01.12 03:37:58 [Server] INFO /* Object: SpongeItemStackSnapshot{itemType=Item{Name=none}, count=1} */ 01.12 03:37:58 [Server] INFO /* - Name: Cursor */ 01.12 03:37:58 [Server] INFO /* Object: net.minecraft.network.play.client.CPacketClientSettings@5c48976e */ 01.12 03:37:58 [Server] INFO /* - Name: Packet */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: PacketPlayer */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Source */ 01.12 03:37:58 [Server] INFO /* - Name: UnwindingContext */ 01.12 03:37:58 [Server] INFO /* Context: */ 01.12 03:37:58 [Server] INFO /* - Phase: org.spongepowered.common.event.tracking.phase.general.PostState@686b08c0 */ 01.12 03:37:58 [Server] INFO /* Phases remaining : */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Notifier */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Owner */ 01.12 03:37:58 [Server] INFO /* Object: false */ 01.12 03:37:58 [Server] INFO /* - Name: IgnoringCreative */ 01.12 03:37:58 [Server] INFO /* Object: SpongeItemStackSnapshot{itemType=Item{Name=none}, count=1} */ 01.12 03:37:58 [Server] INFO /* - Name: Cursor */ 01.12 03:37:58 [Server] INFO /* Object: net.minecraft.network.play.client.CPacketClientSettings@5c48976e */ 01.12 03:37:58 [Server] INFO /* - Name: Packet */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: PacketPlayer */ 01.12 03:37:58 [Server] INFO /* Object: EntityPlayerMP['Zera_Fox'/26926, l='Creatures', x=-16401.83, y=63.00, z=28671.55] */ 01.12 03:37:58 [Server] INFO /* - Name: Source */ 01.12 03:37:58 [Server] INFO /* Affected World : WorldServer{LevelName=Creatures, DimensionId=0, DimensionType=minecraft:overworld} */ 01.12 03:37:58 [Server] INFO /* PhaseContext : */ 01.12 03:37:58 [Server] INFO /* Something happened when trying to unwind org.spongepowered.common.event.tracking.phase.packet.BasicPacketState@27dc5f75 */ 01.12 03:37:58 [Server] INFO /***********************************************************************************************************************************/ 01.12 03:37:58 [Server] INFO /* Exception Exiting Phase */ 01.12 03:37:58 [Server] INFO /***********************************************************************************************************************************/

I'm not 100% sure where this error is coming from, so if I'm in the wrong place please let me know and I'll redirect my error properly. ^.^;

**Comment by Daniel12321** [comment]
I cant find any reference to my plugin in the error. I am quite certain that i also had this same error in a server that didnt have my plugin, so it might be a sponge error

**Comment by Daniel12321** [comment]
Fixed in the new code.
