### ISSUE TITLE
ChangeBlockEvent error

### ISSUE THREAD

**Issue by zerafox** [Daniel12321/AdventureMMO#13]
01.12 03:48:40 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111] 01.12 03:48:40 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?] 01.12 03:48:40 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?] 01.12 03:48:40 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?] 01.12 03:48:40 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?] 01.12 03:48:40 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?] 01.12 03:48:40 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111] 01.12 03:48:40 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111] 01.12 03:48:40 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?] 01.12 03:48:40 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?] 01.12 03:48:40 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:130) [PacketUtil.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:190) [CauseTracker.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:320) [PacketPhase.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$28(PacketFunction.java:424) ~[PacketFunction.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) ~[CapturedSupplier.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$null$23(PacketFunction.java:425) ~[PacketFunction.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:503) ~[TrackingUtil.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:583) ~[TrackingUtil.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:140) ~[SpongeImpl.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) ~[SpongeModEventManager.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:398) ~[SpongeModEventManager.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357) ~[SpongeModEventManager.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2123-5.1.0-BETA-1879] 01.12 03:48:40 [Server] INFO at org.spongepowered.common.event.listener.BreakListener_BlockListener_onBlockBreak52.handle(Unknown Source) ~[?:?] 01.12 03:48:40 [Server] INFO at me.mrdaniel.mmo.listeners.BlockListener.onBlockBreak(BlockListener.java:91) ~[BlockListener.class:?] 01.12 03:48:40 [Server] INFO at me.mrdaniel.mmo.io.players.MMOPlayer.process(MMOPlayer.java:56) ~[MMOPlayer.class:?] 01.12 03:48:40 [Server] INFO at me.mrdaniel.mmo.skills.SkillManager.level(SkillManager.java:31) ~[SkillManager.class:?] 01.12 03:48:40 [Server] INFO at me.mrdaniel.mmo.utils.EffectUtils.send(EffectUtils.java:27) ~[EffectUtils.class:?] 01.12 03:48:40 [Server] INFO java.lang.NoSuchMethodError: org.spongepowered.api.effect.particle.ParticleEffect$Builder.type(Lorg/spongepowered/api/effect/particle/ParticleType;)Lorg/spongepowered/api/effect/particle/ParticleEffect$ParticleBuilder; 01.12 03:48:40 [Server] Server thread/ERROR [Sponge]: Could not pass ChangeBlockEvent$Break$Impl to Plugin{id=adventuremmo, name=AdventureMMO, version=1.6.3, source=/mods/MMO-v1.6.3-API5.0.jar}

**Comment by Daniel12321** [comment]
This should be fixed when updating spongeAPI and by downloading MMO-v1.6.3-API5.x

**Comment by Daniel12321** [comment]
Fixed in the new code.
