### ISSUE TITLE
Limit "you earned" message

### ISSUE THREAD

**Issue by zerafox** [Daniel12321/AdventureMMO#14]
The message for earning money when your skill goes up, most of the time results in "X.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" values and is rather an eyesore.

Would it be possible to have this reduced/limited to only a X.xx display?

**Comment by Daniel12321** [comment]
I will try to do this in the next update

**Comment by EvilCh33z** [comment]
seconded.

**Comment by Daniel12321** [comment]
Fixed in the new code.
