### ISSUE TITLE
Disappearing Items

### ISSUE THREAD

**Issue by zerafox** [Daniel12321/AdventureMMO#15]
It appears that when you move an item in your inventory while a skill is still active, you lose the tool.

I'm providing a link to a Twitch video, which provides a visual for the incident. No errors seem to appear in console when this occurs, however I will try to keep an eye out for any.

https://www.twitch.tv/zimortei/v/104871880

0:51:00 in (roughly) you see when the pickaxe disappears after moving a stack of stone.

**Comment by Daniel12321** [comment]
I have heard some more complaints, i will be looking into this today

**Comment by Daniel12321** [comment]
Fixed in the new code.
