### ISSUE TITLE
Tinker's Construct support.

### ISSUE THREAD

**Issue by Unnoen** [Daniel12321/AdventureMMO#17]
It would be fantastic if you could add support for TConstruct.

**Comment by yepidoodles** [comment]
I second this, along with other mod support.

**Comment by zerafox** [comment]
What makes this incompatible with TConstruct?
Doesn't AdventureMMO allow you to add tools/weapons to configs for mods items?

**Comment by yepidoodles** [comment]
I just assumed as it didn't come pre-installed that it couldn't be added (I mean, who doesn't use Tinkers' Construct)

**Comment by zerafox** [comment]
I didn't until a few day ago. Haha!

Also never assume. ;P Always check. You could've had it all setup hours ago to be completely compatible instead of waiting on a ticket request to only be told it should already work just fine. ^.^

**Comment by yepidoodles** [comment]
I didn't care enough to check, I don't think, haha, my new 1.10.2 server is kicking my ass.

**Comment by Daniel12321** [comment]
Can be easily done using the new code now.
