### ISSUE TITLE
Offhand Triggers Abilities 1.10.2

### ISSUE THREAD

**Issue by Kiibun** [Daniel12321/AdventureMMO#18]
I had a player report this to me on my server where I use Adventure MMO.

> I had a pick in my hand and torches in my offhand, and then the offhand triggers A-MMO (right click is right click I suppose...), well when the first use wears off, after that when I tried to place a torch it would flood my screen with "you must wait" style messages, 20-30 for each right click.

Is there anyway to disable the messages so players don't see them? Or is there a way to disable the use of the abilities when something is in your offhand? I noticed there are little to no config options regarding this issue.

Thanks for the awesome plugin, and hopefully a speedy reply. :)

.

**Comment by Daniel12321** [comment]
This should not be an issue anymore in the new versions.
