### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by yepidoodles** [Daniel12321/AdventureMMO#19]
I keep getting this Error in console, I thought you might want to know.

http://www.codesend.com/view/3b84500a0fc16d5ee8ba2c2e64893840/

I believe it comes up when someone attacks a Vampirism NPC.

- Alice
[DragontechMC](http://dragontechmc.com)

**Comment by yepidoodles** [comment]
Another Error, no idea what this is

http://www.codesend.com/view/b2ae5a89bc1b527679c03b1118e0b028/

**Comment by yepidoodles** [comment]
Oh look, another one

http://www.codesend.com/view/8c5f76139ec22e03a2be783b73a6bb4d/

**Comment by yepidoodles** [comment]
And another...

http://www.codesend.com/view/8f0d8458496c63edeedd831ad84808b0/

**Comment by Daniel12321** [comment]
Fixed in the new code.
