### ISSUE TITLE
Suggestion: Turn off right click messages

### ISSUE THREAD

**Issue by yepidoodles** [Daniel12321/AdventureMMO#20]
Several people (Including myself) find the right click message 'You ready your x' annoying as it comes up whenever you open a chest or something. Perhaps you could add an option to settings to turn that feature off. 

Thanks

- Alice

**Comment by zerafox** [comment]
Or at least put a delay on how often the message appears?
Or better yet, check for an interaction event before sending the message? "If player interacts with X, do not ready X" sort of thing?
I too find it rather spammy.

**Comment by Brend-Smits** [comment]
Same, any idea when this is being added/fixed? 
Will not be using the plugin currently because of this spam

**Comment by yepidoodles** [comment]
The plugin hasn't been updated since November, seems abandoned

**Comment by Brend-Smits** [comment]
Damn @yepidoodles any similar plugins that you suggest?

**Comment by yepidoodles** [comment]
Unfortunately not, I've been on the lookout though.

**Comment by Daniel12321** [comment]
This message has been removed in the new code.
