### ISSUE TITLE
What version is this for?

### ISSUE THREAD

**Issue by NineDivinez** [Daniel12321/AdventureMMO#21]
I'm trying to get sponge to work on my server, finally got the server to actually start, but now your plugin isn't working with commands.  Info would be be a great help, thank you! :)

**Comment by Daniel12321** [comment]
Are you getting any errors? If so, please send them to me.
The latest version should work for sponge API 5.x and 6.x. It probably wont work for 4.x

**Comment by NineDivinez** [comment]
No errors that I can see.  Just gave me command not found nonsense.
