### ISSUE TITLE
Infinite Durability Tools

### ISSUE THREAD

**Issue by ChetwyndKid** [Daniel12321/AdventureMMO#22]
Hi,
Was playing using Pixelmon 5.0.2 and have this plugin installed. Somehow I ended up with Infinite durability tools with the effects perm on them. 
http://prntscr.com/enz9pf
http://prntscr.com/enz9sw

(Might be switching tools while ability is in effect, Or logging off)
Not sure how I managed this but I can try to re-produce if needed.

**Comment by Daniel12321** [comment]
Hmm, i tried it myself and i could not managed to get them. They should at the very least be ghost item, meaning if you put them in a chest or relog they should go back to normal. Can you try that?

They get these effects when activating the Mad Miner, Giga Drill or Fish Craze ability by the way.

**Comment by ChetwyndKid** [comment]
Yeah im aware how how to get them.
They did not remove and relog and I could not move them to a chest. I had to empty my inventory other then the tools and had to /clear my inventory to get rid of them as they would not allow me to move them from my inventory.

**Comment by Daniel12321** [comment]
This will be fixed when i upload v2.0.5.
