### ISSUE TITLE
Using Abilities wipes other enchants from tools

### ISSUE THREAD

**Issue by ChetwyndKid** [Daniel12321/AdventureMMO#23]
Hey,
Using this I decided to enchant a diamond pick
When I activated the ability on my shovel it removed the enchant from the pick?
It seems the plugin not only removes its own enchantments but other enchantments also?

**Comment by Daniel12321** [comment]
Did you enchant it while the effect was active? If so, the enchantment would be removed. Else the enchantment will stay.
