### ISSUE TITLE
Tree feller

### ISSUE THREAD

**Issue by aWitch-Doctor** [Daniel12321/AdventureMMO#25]
In version 2.0.6 for api 5.  Tree feller does not work until the config.conf is edited, the tree feller ability is listed as tree veller. Change this to tree feller and it works fine. This is more for people installing the plugin then the creator.

I do have a request for the creator. Can you make it so the tree feller ability breaks the blocks below the one you break of the tree? Right now it will break all blocks at and above the one you break but not below. Not an issue just a request.

Thank you for your hard work.

**Comment by Daniel12321** [comment]
Hmm weird, i thought i changed that... Well it will be changed in the next version then

**Comment by Daniel12321** [comment]
I reuploaded the download files, and changed it to the correct name. Anyone that downloads it now will get the good one.

**Comment by aWitch-Doctor** [comment]
Nice, thank you.
