### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by yepidoodles** [Daniel12321/AdventureMMO#26]
http://www.codesend.com/view/b037461f3ee35c867ab3488f9d75f32d/

`com.brandon3055.draconicevolution.blocks.tileentity.TileGrinder.updateGrinding`

AdventureMMO version: 2.0.6
SpongeForge version: spongeforge-1.10.2-2221-5.2.0-BETA-2229
Forge Version: 2221

**Comment by yepidoodles** [comment]
`[19:50:36] [Server thread/ERROR] [Sponge/]: Could not pass PlayerDamageEntityEvent to Plugin{id=adventuremmo, name=AdventureMMO, version=2.0.6, description=A light-weight plugin that adds skills with all sorts of fun game mechanics to your server., authors=[Daniel12321], source=C:\Users\DragonTech\Desktop\DragonIndustries3\mods\AdventureMMO-v2.0.6-API5.jar}
java.lang.NullPointerException`

**Comment by Daniel12321** [comment]
The codesend link doesnt seem to work, can you send me the full error another way?

**Comment by yepidoodles** [comment]
Weird, works fine for me, but here

https://pastebin.com/rLLLK8F0

**Comment by Daniel12321** [comment]
Are there any earlier errors? Specifically on player login?

**Comment by yepidoodles** [comment]
No

The 2nd error has been happening over and over for hours without any players being online, there are chunks loaded so I'm assuming it's someone's mob spawner, maybe a killer joe from EnderIO

**Comment by Daniel12321** [comment]
It looks like some mods use fake players to kill mobs, which causes an error because the playerdata was never loaded. I will try to find an efficiënt sollution soon.

**Comment by Daniel12321** [comment]
The version with this fix was just released.
