### ISSUE TITLE
Using Sword levels up Axe Skill

### ISSUE THREAD

**Issue by yepidoodles** [Daniel12321/AdventureMMO#28]
Several of my players have reported the same

https://gyazo.com/91a8c5ee0e3394328ecd11be1b4bc00f

**Comment by Daniel12321** [comment]
Hmm, weird, ill look into it

**Comment by Daniel12321** [comment]
Okey, i found the problem. Will be fixed in 2.0.7, which i will release in a few hours.

**Comment by Daniel12321** [comment]
The version with this fix was just released.
