### ISSUE TITLE
Another Console error

### ISSUE THREAD

**Issue by yepidoodles** [Daniel12321/AdventureMMO#29]
AdventureMMO version: 2.0.7
SpongeForge version: spongeforge-1.10.2-2221-5.2.0-BETA-2229
Forge Version: 2221

Pretty sure this is new to 2.0.7

https://pastebin.com/mp8GXrmZ

**Comment by Daniel12321** [comment]
Weird, i cant find anything that would cause this. Did it happen once or multiple times?

**Comment by yepidoodles** [comment]
Closing due to being abandoned.
