### ISSUE TITLE
[Request] Ore Dictionary Support

### ISSUE THREAD

**Issue by yepidoodles** [Daniel12321/AdventureMMO#31]
I've been trying to add modded items to the config, and noticed that it does not support Meta Data or Ore dict.

I'd really like to add Copper ore from Forestry but it either needs Meta Data or Ore dict.
`forestry:resources:1`  
`ore:oreCopper`  

If I use the command, it adds it as simply `forestry:resources` which is Apatite, worth much less.

**Comment by Daniel12321** [comment]
Minecraft wants to get rid of the meta data values soon, and sponge has already been preparing for that a lot. Meaning working with these metadata values in sponge is difficult and not adviced. I will try to see what i can do, but it will be difficult.

**Comment by Brend-Smits** [comment]
I would like to see this feature being added as well. Currently it's not worth adding it to my server for vanilla only items =/

**Comment by yepidoodles** [comment]
I'm happy to forget about Meta if Ore Dict is possible?

**Comment by Daniel12321** [comment]
I think i have to integrate the plugin with forge if i want to do that, which is a pain. Ill see what i can do though.

**Comment by Daniel12321** [comment]
I think i found a way to do it. Im trying to get it to work now. Its quite a big change, so dont expect it this week.

**Comment by yepidoodles** [comment]
Closing due to being abandoned.

**Comment by MadHalaster** [comment]
As a side note, someone else did pick it up and started work on it, but after two days the links were all removed, since Daniel has yet to actually add a License to this so someone else can continue work unfortunately. A request has been put in for him to add a license, he just has to confirm it.

**Comment by yepidoodles** [comment]
Yeah I saw it, but based on the fact he hasn't been seen in forever, I doubt he'll see it before someone just decides to make their own. I was also just clearing out my old issues so it's easier to keep track of the ones which might actually get fixed within the next year, haha.
