### ISSUE TITLE
[1.10.2]Could not pass events

### ISSUE THREAD

**Issue by FiveEYZ** [Daniel12321/AdventureMMO#5]
A player leveled up in woodcutting and this was generated in console
https://gist.github.com/FiveEYZ/889764401ef94e34dbb2a189b3fde61c

Tried to activate my pickaxe "Super Breaker"
https://gist.github.com/FiveEYZ/a9a40ef6ea92f2bd895217966d3e615c

**Comment by FiveEYZ** [comment]
also activated "Tree Feller!" and it never ends

tried to relogg but the skill was still active

**Comment by Daniel12321** [comment]
Try to update your Sponge

**Comment by Daniel12321** [comment]
The Tree Veller not deactiviating is because it gave an error on the particle effect building.

**Comment by Daniel12321** [comment]
Fixed in the newest version
