### ISSUE TITLE
Improvement Request: Add Support for Biomes O' Plenty Blocks

### ISSUE THREAD

**Issue by MadHalaster** [Daniel12321/AdventureMMO#9]
This is just a request to add support for the Biomes O' Plenty blocks, which is a fairly popular biome mod. It adds quite a few new block types as well and none of the abilities seem to trigger properly when interacting with any of the new blocks. For example there are 18 new tree types and when using an axe it just triggers "Slaughter" instead of "Tree Feller".

This was something that was supported in McMMO and I am hoping you can implement it as well.
If not directly into the mod, then perhaps as an add-on or compatibility pack.

If you cannot implement this, then pointing me in the direction of how to edit in support for these items and I can probably sort that out myself.

**Comment by MadHalaster** [comment]
I see in the WatchList.java you have all of the blocks you are watching, but without a prefix. In the game the base blocks are all minecraft:log, minecraft:clay, and so on.

For all of the blocks from biomes o plenty they have a different prefix. Specifically biomesoplenty:log_0 as an example. If just log_0 was added to the watchlist would it work without knowing the prefix?
For wood the new blocks are: log_0, log_1, log_2, log_3, log_4
For leaves the new blocks are: leaves_0, leaves_1, leaves_2, leaves_3, leaves_4, leaves_5
New gems are: crystal, biome_block. and gem_ore 
gem_ore has the following variants, which again I am not sure if that matters for the purpose of the watch list: Ender Amethyst, Ruby, Peridot, Topaz, Tanzanite, Amber, and Sapphire

New dirt type blocks: mud, dried_sand, ash_block, flesh, dirt
Dirt variants: loamy, daisy, overgrown_netherraack, origin, silty, sandy, overgrown_stone, spectral_moss

New stones: crag_rock, stone
Stone variants: shale, siltstone, limestone

Even a basic implementation of ability support would be great. I understand that full support of detailed exp values would be more complicated as you are not aware of the rarity of each new item.

**Comment by zerafox** [comment]
There is a config file to add custom blocks, just like items.
Though I'm not 100% sure it's reading the biomesoplenty:<item> properly, as I'm getting errors myself on startup. o.o

**Comment by Daniel12321** [comment]
Done in the new code.
